# Author:  Iain Bancarz, ib5@sanger.ac.uk
# July 2012

use strict;
use warnings;
use Carp;
use File::Temp qw/tempdir/;
use FindBin qw($Bin);
use Test::More tests => 10;
use JSON;
use WTSI::Genotyping::QC::Reports qw(createReports);
use WTSI::Genotyping::QC::QCPlotShared qw/defaultJsonConfig/;

my $sup = "qc/alpha/supplementary";

# requires input paths to pipeline DB and QC results JSON
# assumes these have been generated by qc_alpha.t
# TODO make reports.t self-contained by storing copies of input files

#my $resultPath = "$Bin/$sup/qc_results.json";
#my $dbPath = "$Bin/qc_test_data/alpha_pipeline.db";
#my $gtPath = "$Bin/$sup/sample_xhet_gender_thresholds.txt";
#my $texPath = "$Bin/$sup/report_test_pipeline_summary.tex";
#my $pdfPath = "$Bin/$sup/report_test_pipeline_summary.pdf";
#my $csvPath = "$Bin/$sup/report_test_pipeline_summary.csv";
#my $qcDir = "$Bin/$sup/";
my $qcName = "alpha";
my $title = "";
my $author = "";
my $introPath = "$Bin/../etc/reportIntro.tex";
my $config = defaultJsonConfig();

my $inputdir = "$Bin/reports/";
my $dbName = "pipeline.db";
my $resultName = "qc_results.json";
my $gtName = "sample_xhet_gender_thresholds.txt";
my $tempdir = tempdir(CLEANUP => 0);
print "Temporary report directory: $tempdir\n";
my $cmd = "cp $inputdir$dbName $inputdir$resultName $inputdir$gtName ".
    "${inputdir}*.pdf $tempdir";
if (system($cmd)!=0) { 
    croak "Cannot copy input files to temporary directory!"; 
}
my $dbPath = $tempdir."/".$dbName;
my $resultPath = $tempdir."/".$resultName;
my $gtPath = $tempdir."/".$gtName;
my $prefix = $tempdir."/report_test_pipeline_summary";
my $texPath = $prefix.".tex";
my $pdfPath = $prefix.".pdf";
my $csvPath = $prefix.".csv";

my @text = WTSI::Genotyping::QC::Reports::textForDatasets($dbPath);
ok(@text, "Read database dataset info");

my $result = WTSI::Genotyping::QC::Reports::dbSampleInfo($dbPath);
ok($result, "Read database sample info");

my ($sumRef, $keyRef, $countRef, $rateRef) = 
    WTSI::Genotyping::QC::Reports::textForPlates($resultPath, $config);
# expect exactly 13 lines, including header
is(@{$countRef}, 13, "Find pass/fail count table text"); 
is(@{$rateRef}, 13, "Find pass/fail rate table text"); 

my @csvText = WTSI::Genotyping::QC::Reports::textForCsv($resultPath, $dbPath, 
                                                        $config);
is(@csvText, 996, "Find CSV text"); # expect 996 lines, including header

ok(WTSI::Genotyping::QC::Reports::writeCsv($resultPath, $dbPath, $config, 
                                           $csvPath), "Write CSV text"); 

ok(WTSI::Genotyping::QC::Reports::writeSummaryLatex
   ($texPath, $resultPath, $config, $dbPath, $gtPath, $tempdir, $introPath, 
    $qcName, $title, $author), "Write summary .tex");

if (-e $pdfPath) { system("rm -f $pdfPath"); }

ok(WTSI::Genotyping::QC::Reports::texToPdf($texPath), "Convert .tex to .pdf");

ok((-e $pdfPath), "PDF file exists");

ok(createReports($csvPath, $texPath, $resultPath, $config, $dbPath, $gtPath, 
                 $tempdir, $introPath, $qcName, $title, $author), 
   "Main method to create CSV and PDF reports");

