* Header
** Title
   How to create an artificial genotyping test dataset
** Author
   Iain Bancarz, ib5@sanger.ac.uk
** Created
   2012-11-16
** Updated
   2012-11-16

* Introduction
  The test datasets for genotyping QC are made up of artificial data.  This avoids any confidentiality issues which would arise from using real biological samples.  This document is a rough outline of how the test datasets were created, for future reference.

Test datasets consist of randomly generated but "plausible" values, including Plink and .sim data and a SQLite database such as would be created by a successful calling run.  The datasets do not assume any particular calling software was used.

* Plink generation

Run plinkGenerator.py with appropriate arguments.

Typical command line:
python plinkGenerator.py config.xml 1000000 5000 50 0 beta 1

config.xml is an XML file with details of chromosomes and SNP probabilities.

Other arguments:  Distance between SNPs (should have a significant number of SNPs at least 1000000 bases apart to enable duplicate check); total number of samples; number of duplicates; offset of sample count from zero; prefix for sample names; type of name (0 enforces plate_well_id format, 1 doesn't).

This will generate Plink .ped files and convert to .bed binary.  The Plink files will have a plausible rate of heterozygosity.  Samples have a 50% chance of being male, with appropriate low (not necessarily zero) heterozygosity on the X chromosome.  Some samples will also receive a "no call" status.

Note that by default, sample names are generated in URI format, eg. urn:wtsi:SAMPLE_NAME.

* Sim generation

Run simGenerator.py to generate intensity data in .sim (simple intensity matrix) format.  Intensities will have plausible X and Y components for a given genotype, with some degree of noise.

Arguments: Path to Plink .ped file (not .bed) for input; path for .sim output.

* Database generation

Run create_test_database.pl to generate an SQLite database, which can be used to run pipeline QC.

Requires a sample_xhet_gender.txt file as input, which can be generated by running check_xhet_gender.pl on the artificial Plink data.
