#!/usr/bin/perl
use strict;
print 'NOTICE: Release Version = rods3.3, API Version = d
NOTICE: environment variable set, irodsEnvFile=/nfs/users/nfs_d/dj3/.irods/.irodsEnv-dev
NOTICE: irodsHost=irods-sanger1-dev.internal.sanger.ac.uk
NOTICE: irodsPort=1247
NOTICE: irodsDefResource=wtsiusers
NOTICE: irodsHome=/Sanger1-dev/home/dj3
NOTICE: irodsCwd=/Sanger1-dev/home/dj3
NOTICE: irodsUserName=dj3
NOTICE: irodsZone=Sanger1-dev
';
